import axios from "axios";

const fullName = [
  "John Smith",
  "Jane Doe",
  "Michael Johnson",
  "Emily Davis",
  "Chris Brown",
  "Sarah Wilson",
  "David Jones",
  "Laura Miller",
  "James Taylor",
  "Emma Moore",
  "Daniel Anderson",
  "Olivia Thomas",
  "Matthew Harris",
  "Sophia Martin",
  "Joshua Thompson",
  "Isabella Martinez",
  "Ethan White",
  "Mia Garcia",
  "Alexander Clark",
  "Ava Rodriguez",
  "Liam Lewis",
  "Charlotte Walker",
  "Noah Hall",
  "Amelia Young",
  "William King",
  "Harper Wright",
  "Benjamin Scott",
  "Abigail Green",
  "Lucas Adams",
  "Avery Baker",
  "Henry Nelson",
  "Ella Carter",
  "Jack Mitchell",
  "Grace Perez",
  "Samuel Roberts",
  "Chloe Turner",
  "Mason Phillips",
  "Lily Campbell",
  "Jackson Parker",
  "Victoria Evans",
  "Sebastian Edwards",
  "Scarlett Collins",
  "Logan Stewart",
  "Hannah Sanchez",
  "Jacob Rivera",
  "Zoey Morris",
  "Elijah Price",
  "Aria Rogers",
  "Owen Reed",
  "Penelope Cook",
  "Caleb Bailey",
  "Layla Murphy",
  "Nathan Hughes",
  "Lillian Richardson",
  "Isaac Ward",
  "Natalie Cox",
  "Gabriel Howard",
  "Camila Morgan",
  "Julian Cooper",
  "Ellie Bell",
  "Levi Peterson",
  "Samantha Bailey",
  "Adam Foster",
  "Mila Gonzalez",
  "Andrew Ross",
  "Riley Simmons",
  "Joseph Diaz",
  "Aubrey Bryant",
  "Ryan Ramirez",
  "Zoe Barnes",
  "Luke Kelly",
  "Madison Coleman",
  "Asher Henderson",
  "Luna Graham",
  "Jayden Butler",
  "Evelyn Fisher",
  "Aiden Torres",
  "Nora Griffin",
  "Carter Sanders",
  "Scarlett Hayes",
  "Wyatt Long",
  "Maya Price",
  "Dylan Ward",
  "Hazel Bennett",
  "Grayson Brooks",
  "Savannah Russell",
  "Isaiah Warren",
  "Stella Griffin",
  "Oliver Chavez",
  "Lily Reed",
  "Anthony Jenkins",
  "Eleanor Crawford",
  "Charles West",
  "Ariana Edwards",
  "Thomas Gordon",
  "Violet Fox",
  "Ezra Diaz",
  "Lucy Flores",
  "Christopher Wood",
  "Alice Stewart",
  "Nolan Bryant",
  "Ruby Mason",
  "Eli Moore",
  "Mackenzie Watson",
  "Hudson Perry",
];

const userName = [
  "johnsmith01",
  "janedoe22",
  "mike_johnson33",
  "emilydavis44",
  "chrisbrown55",
  "sarahwilson66",
  "dave_jones77",
  "laura_miller88",
  "james_taylor99",
  "emma_moore100",
  "dan_anderson11",
  "olivia_thomas12",
  "matt_harris13",
  "sophia_martin14",
  "josh_thompson15",
  "bella_martinez16",
  "ethan_white17",
  "mia_garcia18",
  "alex_clark19",
  "ava_rodriguez20",
  "liam_lewis21",
  "charlotte_walker22",
  "noah_hall23",
  "amelia_young24",
  "will_king25",
  "harper_wright26",
  "ben_smith27",
  "abi_green28",
  "lucas_adams29",
  "avery_baker30",
  "henry_nelson31",
  "ella_carter32",
  "jack_mitchell33",
  "grace_perez34",
  "sam_roberts35",
  "chloe_turner36",
  "mason_phillips37",
  "lily_campbell38",
  "jax_parker39",
  "vic_evans40",
  "seb_edwards41",
  "scarlett_collins42",
  "logan_stewart43",
  "hannah_sanchez44",
  "jake_rivera45",
  "zoey_morris46",
  "eli_price47",
  "aria_rogers48",
  "owen_reed49",
  "penny_cook50",
  "caleb_bailey51",
  "layla_murphy52",
  "nate_hughes53",
  "lily_richardson54",
  "isaac_ward55",
  "nat_cox56",
  "gabe_howard57",
  "cam_morgan58",
  "jules_cooper59",
  "ellie_bell60",
  "levi_peterson61",
  "sam_bailey62",
  "adam_foster63",
  "mila_gonzalez64",
  "andy_ross65",
  "riley_simmons66",
  "joe_diaz67",
  "aubrey_bryant68",
  "ryan_ramirez69",
  "zoe_barnes70",
  "luke_kelly71",
  "madi_coleman72",
  "asher_henderson73",
  "luna_graham74",
  "jayden_butler75",
  "evie_fisher76",
  "aidan_torres77",
  "nora_griffin78",
  "carter_sanders79",
  "scarlett_hayes80",
  "wyatt_long81",
  "maya_price82",
  "dylan_ward83",
  "hazel_bennett84",
  "grayson_brooks85",
  "savannah_russell86",
  "isaiah_warren87",
  "stella_griffin88",
  "oliver_chavez89",
  "lily_reed90",
  "tony_jenkins91",
  "ellie_crawford92",
  "charlie_west93",
  "ariana_edwards94",
  "thomas_gordon95",
  "violet_fox96",
  "ezra_diaz97",
  "lucy_flores98",
  "chris_wood99",
  "alice_stewart100",
  "nolan_bryant101",
  "ruby_mason102",
  "eli_moore103",
  "mackenzie_watson104",
  "hudson_perry105",
];

const email = [
  "johnsmith01@example.com",
  "janedoe22@example.com",
  "mike.johnson33@example.com",
  "emily.davis44@example.com",
  "chris.brown55@example.com",
  "sarah.wilson66@example.com",
  "dave.jones77@example.com",
  "laura.miller88@example.com",
  "james.taylor99@example.com",
  "emma.moore100@example.com",
  "dan.anderson11@example.com",
  "olivia.thomas12@example.com",
  "matt.harris13@example.com",
  "sophia.martin14@example.com",
  "josh.thompson15@example.com",
  "bella.martinez16@example.com",
  "ethan.white17@example.com",
  "mia.garcia18@example.com",
  "alex.clark19@example.com",
  "ava.rodriguez20@example.com",
  "liam.lewis21@example.com",
  "charlotte.walker22@example.com",
  "noah.hall23@example.com",
  "amelia.young24@example.com",
  "will.king25@example.com",
  "harper.wright26@example.com",
  "ben.smith27@example.com",
  "abi.green28@example.com",
  "lucas.adams29@example.com",
  "avery.baker30@example.com",
  "henry.nelson31@example.com",
  "ella.carter32@example.com",
  "jack.mitchell33@example.com",
  "grace.perez34@example.com",
  "sam.roberts35@example.com",
  "chloe.turner36@example.com",
  "mason.phillips37@example.com",
  "lily.campbell38@example.com",
  "jax.parker39@example.com",
  "vic.evans40@example.com",
  "seb.edwards41@example.com",
  "scarlett.collins42@example.com",
  "logan.stewart43@example.com",
  "hannah.sanchez44@example.com",
  "jake.rivera45@example.com",
  "zoey.morris46@example.com",
  "eli.price47@example.com",
  "aria.rogers48@example.com",
  "owen.reed49@example.com",
  "penny.cook50@example.com",
  "caleb.bailey51@example.com",
  "layla.murphy52@example.com",
  "nate.hughes53@example.com",
  "lily.richardson54@example.com",
  "isaac.ward55@example.com",
  "nat.cox56@example.com",
  "gabe.howard57@example.com",
  "cam.morgan58@example.com",
  "jules.cooper59@example.com",
  "ellie.bell60@example.com",
  "levi.peterson61@example.com",
  "sam.bailey62@example.com",
  "adam.foster63@example.com",
  "mila.gonzalez64@example.com",
  "andy.ross65@example.com",
  "riley.simmons66@example.com",
  "joe.diaz67@example.com",
  "aubrey.bryant68@example.com",
  "ryan.ramirez69@example.com",
  "zoe.barnes70@example.com",
  "luke.kelly71@example.com",
  "madi.coleman72@example.com",
  "asher.henderson73@example.com",
  "luna.graham74@example.com",
  "jayden.butler75@example.com",
  "evie.fisher76@example.com",
  "aidan.torres77@example.com",
  "nora.griffin78@example.com",
  "carter.sanders79@example.com",
  "scarlett.hayes80@example.com",
  "wyatt.long81@example.com",
  "maya.price82@example.com",
  "dylan.ward83@example.com",
  "hazel.bennett84@example.com",
  "grayson.brooks85@example.com",
  "savannah.russell86@example.com",
  "isaiah.warren87@example.com",
  "stella.griffin88@example.com",
  "oliver.chavez89@example.com",
  "lily.reed90@example.com",
  "tony.jenkins91@example.com",
  "ellie.crawford92@example.com",
  "charlie.west93@example.com",
  "ariana.edwards94@example.com",
  "thomas.gordon95@example.com",
  "violet.fox96@example.com",
  "ezra.diaz97@example.com",
  "lucy.flores98@example.com",
  "chris.wood99@example.com",
  "alice.stewart100@example.com",
  "nolan.bryant101@example.com",
  "ruby.mason102@example.com",
  "eli.moore103@example.com",
  "mackenzie.watson104@example.com",
  "hudson.perry105@example.com",
];

const datesOfBirth = [
  { year: 1990, month: 1, day: 15 },
  { year: 1991, month: 2, day: 28 },
  { year: 1992, month: 3, day: 7 },
  { year: 1993, month: 4, day: 19 },
  { year: 1994, month: 5, day: 22 },
  { year: 1995, month: 6, day: 10 },
  { year: 1996, month: 7, day: 14 },
  { year: 1997, month: 8, day: 4 },
  { year: 1998, month: 9, day: 9 },
  { year: 1991, month: 2, day: 28 },
  { year: 1992, month: 3, day: 7 },
  { year: 1993, month: 4, day: 19 },
  { year: 1994, month: 5, day: 22 },
  { year: 1995, month: 6, day: 10 },
  { year: 1996, month: 7, day: 14 },
  { year: 1997, month: 8, day: 4 },
  { year: 1998, month: 9, day: 9 },
  { year: 1999, month: 10, day: 31 },
  { year: 1989, month: 11, day: 2 },
  { year: 1988, month: 12, day: 21 },
  { year: 1987, month: 1, day: 8 },
  { year: 1986, month: 2, day: 15 },
  { year: 1985, month: 3, day: 3 },
  { year: 1984, month: 4, day: 11 },
  { year: 1983, month: 5, day: 17 },
  { year: 1982, month: 6, day: 24 },
  { year: 1981, month: 7, day: 5 },
  { year: 1980, month: 8, day: 19 },
  { year: 1979, month: 9, day: 28 },
  { year: 1978, month: 10, day: 14 },
  { year: 1977, month: 11, day: 30 },
  { year: 1976, month: 12, day: 18 },
  { year: 1975, month: 1, day: 23 },
  { year: 1974, month: 2, day: 7 },
  { year: 1973, month: 3, day: 21 },
  { year: 1972, month: 4, day: 12 },
  { year: 1971, month: 5, day: 25 },
  { year: 1970, month: 6, day: 8 },
  { year: 1969, month: 7, day: 20 },
  { year: 1968, month: 8, day: 31 },
  { year: 1967, month: 9, day: 2 },
  { year: 1966, month: 10, day: 15 },
  { year: 1965, month: 11, day: 26 },
  { year: 1964, month: 12, day: 10 },
  { year: 1963, month: 1, day: 16 },
  { year: 1962, month: 2, day: 28 },
  { year: 1961, month: 3, day: 19 },
  { year: 1960, month: 4, day: 7 },
  { year: 1959, month: 5, day: 30 },
  { year: 1958, month: 6, day: 14 },
  { year: 1957, month: 7, day: 9 },
  { year: 1956, month: 8, day: 25 },
  { year: 1955, month: 9, day: 3 },
  { year: 1954, month: 10, day: 27 },
  { year: 1953, month: 11, day: 13 },
  { year: 1952, month: 12, day: 1 },
  { year: 1951, month: 1, day: 5 },
  { year: 1950, month: 2, day: 18 },
  { year: 1949, month: 3, day: 6 },
  { year: 1948, month: 4, day: 22 },
  { year: 1947, month: 5, day: 10 },
  { year: 1946, month: 6, day: 2 },
  { year: 1945, month: 7, day: 13 },
  { year: 1944, month: 8, day: 31 },
  { year: 1943, month: 9, day: 17 },
  { year: 1942, month: 10, day: 8 },
  { year: 1941, month: 11, day: 26 },
  { year: 1940, month: 12, day: 11 },
  { year: 1939, month: 1, day: 23 },
  { year: 1938, month: 2, day: 4 },
  { year: 1937, month: 3, day: 16 },
  { year: 1936, month: 4, day: 27 },
  { year: 1935, month: 5, day: 19 },
  { year: 1934, month: 6, day: 1 },
  { year: 1933, month: 7, day: 7 },
  { year: 1932, month: 8, day: 28 },
  { year: 1931, month: 9, day: 15 },
  { year: 1930, month: 10, day: 9 },
  { year: 1929, month: 11, day: 20 },
  { year: 1928, month: 12, day: 31 },
  { year: 1927, month: 1, day: 11 },
  { year: 1926, month: 2, day: 3 },
  { year: 1925, month: 3, day: 22 },
  { year: 1924, month: 4, day: 18 },
  { year: 1923, month: 5, day: 2 },
  { year: 1922, month: 6, day: 14 },
  { year: 1921, month: 7, day: 5 },
  { year: 1920, month: 8, day: 12 },
  { year: 1919, month: 9, day: 3 },
  { year: 1918, month: 10, day: 16 },
  { year: 1917, month: 11, day: 7 },
  { year: 1916, month: 12, day: 25 },
  { year: 1915, month: 1, day: 6 },
  { year: 1914, month: 2, day: 19 },
  { year: 1913, month: 3, day: 4 },
  { year: 1912, month: 4, day: 27 },
  { year: 1911, month: 5, day: 31 },
  { year: 1910, month: 6, day: 13 },
  { year: 1909, month: 7, day: 20 },
  { year: 1908, month: 8, day: 11 },
  { year: 1907, month: 9, day: 8 },
  { year: 1906, month: 10, day: 22 },
  { year: 1905, month: 11, day: 10 },
  { year: 1904, month: 12, day: 3 },
];

const password = "YourCommonPassword123";
const numberOfUsers = 40;

async function registerUser(userData) {
  try {
    const response = await axios.post(
      "http://localhost:5000/api/auth/register",
      userData
    );
    console.log(`Registered ${userData.fullName}: ${response.status}`);
  } catch (error) {
    console.log(
      `Failed to register ${userData.fullName}: ${
        error.response?.status || error.message
      }`
    );
  }
}

async function registerUsers() {
  for (let i = 0; i < numberOfUsers; i++) {
    const userData = {
      fullName: fullName[i],
      username: userName[i],
      email: email[i],
      password: password,
      dateOfBirth: datesOfBirth[i],
    };

    await registerUser(userData);
  }
}

registerUsers();
